# Generated by Django 5.1 on 2024-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('category', models.TextField(choices=[('CHAN', 'Changes'), ('TIPS', 'Tips'), ('NEWS', 'News')], max_length=4, verbose_name='Category')),
                ('heading', models.TextField(verbose_name='Heading')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('affected', models.TextField(verbose_name='Who is affected')),
                ('consecuences', models.TextField(verbose_name='Consecuences')),
                ('image', models.ImageField(upload_to='blog')),
            ],
        ),
    ]
