# Generated by Django 5.1 on 2024-09-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
