# Generated by Django 5.1 on 2024-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='affected',
            field=models.TextField(blank=True, null=True, verbose_name='Who is affected'),
        ),
        migrations.AlterField(
            model_name='post',
            name='consecuences',
            field=models.TextField(blank=True, null=True, verbose_name='Consecuences'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.TextField(blank=True, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
    ]
